--<ScriptOptions statementTerminator=";"/>

CREATE TABLE registered_user (
	USER_ID INTEGER UNSIGNED NOT NULL,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	CITY VARCHAR(45) NOT NULL,
	PHONE_NUMBER DECIMAL(10 , 0) NOT NULL,
	PRIMARY KEY (USER_ID)
) ENGINE=InnoDB;

ALTER TABLE registered_user ADD PRIMARY KEY (USER_ID);

